spring:
    datasource:
        url: jdbc:mysql://localhost:3306/bbuddytest?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    jpa:
        properties:
            hibernate:
                default_schema: bbuddytest
server:
  port: 4000